apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mediabasket.fullname" . }}-secret
  labels:
    {{- include "mediabasket.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET_KEY: {{ .Values.env.JWT_SECRET_KEY | b64enc | quote }}
  SECRET_KEY: {{ .Values.env.SECRET_KEY | b64enc | quote }}
  {{- if not .Values.postgres.enabled }}
  DATABASE_PASSWORD: {{ .Values.env.DATABASE_URL | b64enc | quote }}
  {{- else }}
  POSTGRES_PASSWORD: "cGFzc3dvcmQ=" 
  {{- end }}
