apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mediabasket.fullname" . }}-backend
  labels:
    {{- include "mediabasket.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
